// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp_cfBYZs4rSmbAGJO9dB33gZDXJtKaLQ',
    appId: '1:275268611789:web:8fa680893e2199b91c8384',
    messagingSenderId: '275268611789',
    projectId: 'act14-7c51f',
    authDomain: 'act14-7c51f.firebaseapp.com',
    storageBucket: 'act14-7c51f.firebasestorage.app',
    measurementId: 'G-Y83VVJ81CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAscnDHGq78atE9Ev8jefgPOl3BLu6Nmhk',
    appId: '1:275268611789:android:9807dd0577d91c7e1c8384',
    messagingSenderId: '275268611789',
    projectId: 'act14-7c51f',
    storageBucket: 'act14-7c51f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuW5LS0BH3nMvG8Pw6W47DXEetRX413K0',
    appId: '1:275268611789:ios:2b23bca575c011bb1c8384',
    messagingSenderId: '275268611789',
    projectId: 'act14-7c51f',
    storageBucket: 'act14-7c51f.firebasestorage.app',
    iosBundleId: 'com.example.act14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuW5LS0BH3nMvG8Pw6W47DXEetRX413K0',
    appId: '1:275268611789:ios:2b23bca575c011bb1c8384',
    messagingSenderId: '275268611789',
    projectId: 'act14-7c51f',
    storageBucket: 'act14-7c51f.firebasestorage.app',
    iosBundleId: 'com.example.act14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp_cfBYZs4rSmbAGJO9dB33gZDXJtKaLQ',
    appId: '1:275268611789:web:706207e06f68ada01c8384',
    messagingSenderId: '275268611789',
    projectId: 'act14-7c51f',
    authDomain: 'act14-7c51f.firebaseapp.com',
    storageBucket: 'act14-7c51f.firebasestorage.app',
    measurementId: 'G-423ZK9LXMY',
  );
}
